/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package at.fhv.teamb.symphoniacus.rest;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
